language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: ahhhhmed
  password:
    secure: m4RMrS2UsUqAS71RA9p1taH4T+FhcAA/x67nZ3cQmsjiCWZJqWP6owwMj2GnKGiXHIaH4upulVHQXSPmUp0GRWK+70zjZaWBvsgaRPwQ3IeRwkxrrP0vaJ4cbWMM0zit3ibR9qg6OPIDQraPl29Ikxfh3bafCtjFUUoQpXbYUrKRvtRLFHvHFF/bMI9J9+8q0u3AVP05Dkbexqae6D3PJ5t8GjbjudK7EeqYqydVy1bOMHB7oUCGdTEMbcH5eWUJkvxU8dvSOpD+D5Q+9jdnqxuIvvUAIAVIUwqnSOES5PxeOmW6LycT2Mypt2C0NRTTK9QLDFQZUpY2vmLjgTX4IQJnWBtnBm8J7IJEuOGiz2uj9b8hgGeiuXE2jde/zhGWY7xFC3s77qhtJwE63zJUOnXCrMPC8CyIjfOHQfXODaUP8ZBslUXgn4oe3rcGUqL1x3/zNNbOglvHU4hFvLjoCbaXz6mcw0c0sNB9fY/SZNJDtKRtDhdxQC5UpsYc9VzFNy2tI4tpQ7FA9lBn7bsBBIHR4nG+zR6EHtqKrLIxqRQH6cokQZL7jm5TQCVJq38KtvsC5nPhIISYCzH3n6uOuHdn6YOvL79Ytv26Z19xVEcrI6nhIIST6Ox3elYcN256ItRMxVgpvpO9eA0dLXl+7a85ZCryfgYaruKHTqMFjhA=
  on:
    tags: true
    python: '3.6'
